
<TranslatedText
	xmlns:cws="http://schemas.cordys.com/cws/1.0"
	type="com.cordys.translation.TranslatedText"
	RuntimeDocumentID="3C6AA73A-0114-A1E9-8693-4999F945A626">
	<DocumentID>3C6AA73A-0114-A1E9-8693-4999F9456626</DocumentID>
	<Name>3C6AA73A-0114-A1E9-8693-4999F9456626</Name>
	<Description>Catch Exception</Description>
	<CreatedBy>sysadmin</CreatedBy>
	<CreationDate>2019-01-17T11:51:18.901</CreationDate>
	<Notes/>
	<Text>Catch Exception</Text>
	<Language>
		<uri
			id="484D7EEB-71EF-A1E8-AEF2-1B94B31DA4FA"
		/>
	</Language>
	<TextIdentifier>
		<uri
			id="3C6AA73A-0114-A1E9-8693-4999F944E626"
		/>
	</TextIdentifier>
</TranslatedText>
