
<TextIdentifier
	xmlns:cws="http://schemas.cordys.com/cws/1.0"
	type="com.cordys.translation.TextIdentifier"
	typeVersion="55890f21-u239-76j6-988a-92j7opq6ws09"
	RuntimeDocumentID="B4B676CD-53D8-A1E9-9DED-EB120A134894">
	<DocumentID>B4B676CD-53D8-A1E9-9DED-EB120A130894</DocumentID>
	<Name>B4B676CD-53D8-A1E9-9DED-EB120A130894</Name>
	<Description>Catch Exception</Description>
	<CreatedBy>sysadmin</CreatedBy>
	<CreationDate>2019-05-16T09:28:38.708</CreationDate>
	<Notes/>
	<DefaultText>Catch Exception</DefaultText>
	<TranslationInformation>
		<uri
			id="3C6AA73A-0114-A1E9-9572-202723462636"
		/>
	</TranslationInformation>
	<Translations>
		<uri
			id="B4B676CD-53D8-A1E9-9DED-EB120A138894"
		/>
	</Translations>
</TextIdentifier>
